# docker build -f docker\Dockerfile.monitor -t tep-monitor:dev .
# docker images tep-monitor

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY kafka ./kafka
COPY models ./models
COPY data/metadata ./data/metadata

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.monitoring.main"]
