# docker build -f docker\Dockerfile.inference -t tep-inference:dev .
# docker images tep-inference

FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src ./src
COPY models ./models
COPY data/metadata ./data/metadata

ENV PYTHONPATH=/app

CMD ["python", "-m", "src.inference.main"]